title: KorQuAD
author: Kyoungmin Kim
email: kyoungmin.kim@lgcns.com
description: > # this means to ignore newlines until "baseurl:"
  The Korean Question Answering Dataset

#twitter_username: macrod68
#github_username:  macrod68

sass:
    style: compressed


g-analytics: UA-130873429-1
