title: Popup tweets
description: Minimal plugin for popup tweets window
show_downloads: true
baseurl: "http://korquad.github.io" #change it according to your repository name


code: https://github.com/junlulocky/PopupTweets
zip_url: https://github.com/junlulocky/PopupTweets
tar_url: https://github.com/junlulocky/PopupTweets
github: https://github.com/junlulocky


remote_theme : jekyller/PopupTweets
