title: KORQuAD
description: KOR WIKI QA dataset
show_downloads: true
baseurl: "" #change it according to your repository name


code: http://korquad.github.io
zip_url: http://korquad.github.io
tar_url: http://korquad.github.io
github: http://korquad.github.io


remote_theme : jekyller/PopupTweets
